export const CONST_STATUS = {
    CABIN_IN_USING: "CB_IU",
    CABIN_AVAILABEL: "CB_AVL",
    TRANS_ACTIVE: "TRS_AC",
    TRANS_COMPLETE: "TRS_COM",
    TRANS_TIME_ON: "TRS_T_ON",
    TRANS_PRICE_ON: "TRS_P_ON",
    TRANS_PRICE_OFF: "TRS_P_OFF",
    TRS_COM: "TRANS_COMPLETED",
    TRS_NOT_COM: "TRS_NOT_COM",
    PRI_DE_ACTIVE: "PRI_DE_ACTIVE",
    TRANS_TIME_OFF: "TRS_T_OFF",
    ACTIVE_BLOCK: "BLKON",
    INACTIVE_BLOCK: "IN_AC_BLK",
    CARD_ON: "C_ON",
    CARD_OFF: "C_OFF",
    PRI_ON: "P_ON",
    PRI_OFF: "P_ON",
    CATEGORY_PRICE_ACTIVE: "PRI_CA_ACTIVE"
};

export const CONST_CODE_RES = {
    SUCCESS: 1,
    EMPTY: 0,
    FAIL: -1,
};

export const CONST_MESS_RES = {
    SUCCESS: "Successfully",
    EMPTY: "EMPTY",
    FAIL: "FAILED",
};